server:
  port: 8080
  servlet:
    context-path: /cursomc
  #  h2:
  #    console:
  #      enabled: true
  #      path: /h2-console
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create
h2:
  console:
    enabled: true
    path: /h2-console





spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:~/testDB;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE
    username: sa
    password:
    ddl-auto: create
  mail:
    host: smtp.gmail.com
    username: teste@gmail.com
    password: mypassword
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
            fallback: false
          starttls:
            enable: true
          ssl:
            enable: true



